version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Configure Github credentials
          command: |
            git config user.email "fikfikky@gmail.com"
            git config user.name "coderonfleek"
      - add_ssh_keys:
          fingerprints:
            - "93:6c:8e:15:5a:38:37:a1:3c:de:33:f7:0f:b8:af:4c"
      - run:
          name: Deploy to Azure Web App
          command: |
            git checkout deploy
            git merge main
            git commit -am "$CIRCLE_BRANCH build#$CIRCLE_BUILD_NUM"
            git push --force --set-upstream origin deploy
